# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirbusPlane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=25)),
                ('plane_range', models.CharField(max_length=25)),
                ('seating', models.CharField(max_length=25)),
                ('payload', models.CharField(max_length=25)),
                ('wingspan', models.CharField(max_length=25)),
                ('overall_length', models.CharField(max_length=25)),
                ('overall_height', models.CharField(max_length=25)),
            ],
        ),
    ]
