# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='airbusplane',
            name='id',
        ),
        migrations.AddField(
            model_name='airbusplane',
            name='plane_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planes.Plane'),
            preserve_default=False,
        ),
    ]
