# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=25)),
                ('engines', models.ManyToManyField(related_name='engines', to='planes.Engine')),
            ],
        ),
        migrations.RenameField(
            model_name='airbusplane',
            old_name='model',
            new_name='bulk_hold_volume',
        ),
        migrations.RenameField(
            model_name='airbusplane',
            old_name='payload',
            new_name='thrust',
        ),
        migrations.RemoveField(
            model_name='airbusplane',
            name='id',
        ),
        migrations.AddField(
            model_name='airbusplane',
            name='total_volume',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airbusplane',
            name='plane_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planes.Plane'),
            preserve_default=False,
        ),
    ]
