# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_auto_20161006_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airbusplane',
            old_name='payload',
            new_name='bulk_hold_volume',
        ),
        migrations.AddField(
            model_name='airbusplane',
            name='total_volume',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
