# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0004_auto_20161006_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airbusplane',
            name='engines',
        ),
        migrations.AddField(
            model_name='airbusplane',
            name='engines',
            field=models.ManyToManyField(blank=True, null=True, related_name='engines', to='planes.Engine'),
        ),
    ]
