# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0005_boeingplane'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueBookPlane',
            fields=[
                ('plane_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planes.Plane')),
                ('thrust', models.CharField(max_length=25)),
                ('max_speed_knots', models.CharField(max_length=25)),
                ('recommended_cruise_knots', models.CharField(max_length=25)),
                ('stall_knots_dirty', models.CharField(max_length=25)),
                ('fuel_gal_lbs', models.CharField(max_length=25)),
                ('all_eng_service_ceiling', models.CharField(max_length=25)),
                ('eng_out_service_ceiling', models.CharField(max_length=25)),
                ('all_eng_climb_rate', models.CharField(max_length=25)),
                ('eng_out_climb_rate', models.CharField(max_length=25)),
                ('takeoff_over_50_ft', models.CharField(max_length=25)),
                ('takeoff_ground_run', models.CharField(max_length=25)),
                ('landing_over_50_ft', models.CharField(max_length=25)),
                ('landing_ground_roll', models.CharField(max_length=25)),
                ('gross_weight_lbs', models.CharField(max_length=25)),
                ('empty_weight_lbs', models.CharField(max_length=25)),
                ('overall_length', models.CharField(max_length=25)),
                ('overall_height', models.CharField(max_length=25)),
                ('wingspan', models.CharField(max_length=25)),
                ('plane_range', models.CharField(max_length=25)),
            ],
            bases=('planes.plane',),
        ),
    ]
