# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0005_auto_20161006_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airbusplane',
            name='engines',
        ),
        migrations.RemoveField(
            model_name='airbusplane',
            name='model',
        ),
        migrations.AddField(
            model_name='plane',
            name='engines',
            field=models.ManyToManyField(related_name='engines', to='planes.Engine'),
        ),
        migrations.AddField(
            model_name='plane',
            name='model',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
